"""Update

Revision ID: 0464dac64a3c
Revises: 8abbed1870f8
Create Date: 2025-03-31 15:54:21.348691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0464dac64a3c'
down_revision = '8abbed1870f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('venue',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('banner',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('registration_start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('registration_start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('registration_end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('registration_end_time',
               existing_type=postgresql.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('registration_end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('registration_end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('registration_start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('registration_start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('banner',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('venue',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
