"""Changed Events

Revision ID: 101dd2bbf84b
Revises: 4a14f2a27b91
Create Date: 2025-02-04 09:40:35.261718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101dd2bbf84b'
down_revision = '4a14f2a27b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('registration_start_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('registration_end_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('registration_end_time', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('registration_end_time')
        batch_op.drop_column('registration_end_date')
        batch_op.drop_column('registration_start_time')
        batch_op.drop_column('registration_start_date')

    # ### end Alembic commands ###
