"""Added Tables

Revision ID: 32be0dffc31e
Revises: 732e8c49e3b6
Create Date: 2025-04-01 08:55:27.233291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32be0dffc31e'
down_revision = '732e8c49e3b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['order_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
