"""First Migrate

Revision ID: 39f1bf63aa31
Revises: 
Create Date: 2025-01-31 00:37:50.526097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f1bf63aa31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('User_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('Name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('Email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('Phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('Address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Password_Hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('Profile_Pic', sa.Text(), nullable=True))
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['Email'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('name')
        batch_op.drop_column('address')
        batch_op.drop_column('email')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_email_key', ['email'])
        batch_op.drop_column('Profile_Pic')
        batch_op.drop_column('Password_Hash')
        batch_op.drop_column('Address')
        batch_op.drop_column('Phone')
        batch_op.drop_column('Email')
        batch_op.drop_column('Name')
        batch_op.drop_column('User_id')

    # ### end Alembic commands ###
