"""Update

Revision ID: 5e00dc70b5fe
Revises: 0464dac64a3c
Create Date: 2025-03-31 16:08:15.200711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e00dc70b5fe'
down_revision = '0464dac64a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('Published', 'Unpublished', name='event_status'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
