"""Changed Events

Revision ID: 6dbed2f73d61
Revises: 101dd2bbf84b
Create Date: 2025-02-04 11:04:41.090799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6dbed2f73d61'
down_revision = '101dd2bbf84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=False))
        batch_op.drop_column('time_end')
        batch_op.drop_column('time_start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('time_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('end_time')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_time')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
