"""Added Tables

Revision ID: 732e8c49e3b6
Revises: df7318661a05
Create Date: 2025-04-01 08:51:00.590580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732e8c49e3b6'
down_revision = 'df7318661a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('Incomplete', 'Success', 'Failed', name='transaction_status'), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('razorpay_payment_id')
        batch_op.drop_column('status')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
