"""Update

Revision ID: 8abbed1870f8
Revises: 6dbed2f73d61
Create Date: 2025-03-31 15:18:56.340173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abbed1870f8'
down_revision = '6dbed2f73d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('min_team', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_team', sa.Integer(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('banner',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.drop_column('logo')
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('logo', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('banner',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('max_team')
        batch_op.drop_column('min_team')
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
