"""First Migrate

Revision ID: 9f9090ae2a00
Revises: 39f1bf63aa31
Create Date: 2025-01-31 00:41:16.711698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9090ae2a00'
down_revision = '39f1bf63aa31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('Product_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('Image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Category', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Product_id', name='products_pkey')
    )
    # ### end Alembic commands ###
